name: share_plate
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5

  google_fonts: ^6.2.1


  cupertino_icons: ^1.0.8


  

  flutter_chat_ui: ^1.6.15
  line_icons: ^2.0.3
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  fluttertoast: ^8.2.5
  cloud_firestore: ^5.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  assets:
    - assets/shareplate_rwanda_logo.png
    - assets/shareplate_rwanda_logo.svg
    - assets/shareplate_rwanda_logo_transparent.png
    - assets/shareplate_rwanda_logo_high_quality.jpg
    - assets/shareplate_rwanda_logo_500x500.jpg
    - assets/shareplate_rwanda_logo_transparent.svg

    - assets/sharing_is_caring_logo.png
    - assets/default_profile.jpg

    - assets/shareplate-icon.jpeg
    - assets/shareplateburger1.jpeg
    - assets/getameal.jpeg
    - assets/avatar8.png
    - assets/images/facebook.png
    - assets/images/Google_Icons-09-512.webp
    - assets/images/images.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

    


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

