name: share_plate
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Adding GetX for state management
  get: ^4.6.5

  flutter_chat_ui: ^1.6.15
  line_icons: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/shareplate-icon.jpeg
    - assets/shareplateburger1.jpeg
    - assets/getameal.jpeg
    - assets/avatar8.png
